### PR TITLE
Update Ubuntu packages

### PR DESCRIPTION
**Pull request by pburkholder**
## Changes proposed in this pull request:

- Address # USN-4428-1
- Address # USN-4457-1

## security considerations

1) Address patching and 2) code itself is not a leak as they're publicly known updates that are available.

### CODE REVIEW

**Comment by ChrisMcGowan** [comment]
@pburkholder  & @bengerman13 

So the issue at hand is the current script during an update gets hung on trying to replace `/etc/issue` and `/etc/issue.net` which we deploy our own version with the hardening release: https://github.com/cloud-gov/cg-harden-boshrelease/blob/b4461b30220f3185bbea1515c254c1fc7c707809/jobs/harden/templates/bin/post-deploy#L151-L152

My proposed fix which I tested is to add the following logic at the top of the script:

```
if [ -e /etc/apt/apt.conf.d/cloud-gov ]; then
  echo "cloud.gov dpkg config file already exists!"
else
  cat > /etc/apt/apt.conf.d/cloud-gov <<EOF
  Dpkg::Options {
     "--force-confdef";
     "--force-confold";
     }
EOF
fi
```

This creates a `dpkg` file used durning `apt` operations that does the following: 
-- `force-confold` do not modify the current configuration file, the new version is installed with a `.dpkg-dist` suffix. With this option alone, even configuration files that you have not modified are left untouched. You need to combine it with:
 -- `force-confdef` to let dpkg overwrite configuration files that you have not modified.

I found that config here: https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/

In essence this is another logic step to keep the updates moving forward the best we can so we don't hold up the BOSH VM from coming up and still rely on catching script issues/outliers via the Nessus scans.

Thoughts?

**Comment by bengerman13** [comment]
@ChrisMcGowan that makes sense to me

**Comment by ChrisMcGowan** [comment]
@bengerman13  - added in my block to Peter's change

**Comment by bengerman13** [comment]
:shipit:

**Pull request merged**
